USE [GD2015C1]
GO
--Creamos el esquema

CREATE SCHEMA GD_GESTION_DE_VAGOS;
GO

--Creamos las tablas

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'telemetria_motor')
CREATE TABLE GD_GESTION_DE_VAGOS.telemetria_motor(
ID int IDENTITY PRIMARY KEY,
TEMP_ACEITE decimal(18, 6) not null,
TEMP_AGUA decimal (18, 6) not null,
RPM decimal (18, 6) not null,
POTENCIA decimal (18, 6) not null
);


IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'telemetria_caja_de_cambios')
CREATE TABLE GD_GESTION_DE_VAGOS.telemetria_caja_de_cambios(
ID int IDENTITY PRIMARY KEY,
TEMP_ACEITE decimal (18, 2) not null,
RPM decimal (18, 2) not null,
DESGASTE decimal (18, 2) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'piloto')
CREATE TABLE GD_GESTION_DE_VAGOS.piloto(
ID int IDENTITY PRIMARY KEY,
NOMBRE nvarchar(50) not null,
APELLIDO nvarchar(50) not null,
NACIONALIDAD nvarchar(50) not null,
NACIMIENTO date not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'caja_de_cambios')
CREATE TABLE GD_GESTION_DE_VAGOS.caja_de_cambios(
ID nvarchar(255) PRIMARY KEY,
MODELO nvarchar(50) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'motor')
CREATE TABLE GD_GESTION_DE_VAGOS.motor(
ID nvarchar(255) PRIMARY KEY,
MODELO nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'escuderia')
CREATE TABLE GD_GESTION_DE_VAGOS.escuderia(
ID int IDENTITY PRIMARY KEY,
NOMBRE nvarchar(255) not null,
NACIONALIDAD nvarchar(255) not null
);
IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'auto')
CREATE TABLE GD_GESTION_DE_VAGOS.auto(
ID decimal(18,0) IDENTITY PRIMARY KEY,
ID_ESCUDERIA int REFERENCES GD_GESTION_DE_VAGOS.escuderia  not null,
ID_PILOTO int REFERENCES GD_GESTION_DE_VAGOS.piloto  not null,
ID_MOTOR nvarchar(255) REFERENCES GD_GESTION_DE_VAGOS.motor  not null,
ID_CAJA nvarchar(255) REFERENCES GD_GESTION_DE_VAGOS.caja_de_cambios  not null,
MODELO nvarchar(255) not null,
NUMERO int not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'freno')
CREATE TABLE GD_GESTION_DE_VAGOS.freno(
ID nvarchar(255) PRIMARY KEY,
ID_AUTO decimal(18,0) REFERENCES GD_GESTION_DE_VAGOS.auto  not null,
TAMANIO_DISCO decimal(18,2) not null,
POSICION nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'tipo_neumatico')
CREATE TABLE GD_GESTION_DE_VAGOS.tipo_neumatico(
ID int IDENTITY PRIMARY KEY,
NOMBRE nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'neumatico')
CREATE TABLE GD_GESTION_DE_VAGOS.neumatico(
ID int IDENTITY PRIMARY KEY,
ID_AUTO decimal(18,0) REFERENCES GD_GESTION_DE_VAGOS.auto  not null,
ID_TIPO_NEUMATICO int REFERENCES GD_GESTION_DE_VAGOS.tipo_neumatico  not null,
POSICION nvarchar(255) not null,
ESTA_EN_USO bit not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'pais')
CREATE TABLE GD_GESTION_DE_VAGOS.pais(
ID int IDENTITY PRIMARY KEY,
NOMBRE nvarchar(255) not null
);


IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'circuito')
CREATE TABLE GD_GESTION_DE_VAGOS.circuito(
ID int IDENTITY PRIMARY KEY,
ID_PAIS int REFERENCES GD_GESTION_DE_VAGOS.pais not null,
NOMBRE nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'carrera')
CREATE TABLE GD_GESTION_DE_VAGOS.carrera(
    ID int IDENTITY PRIMARY KEY,
    ID_CIRCUITO int REFERENCES GD_GESTION_DE_VAGOS.circuito not null,
    FECHA date not null,
    MAX_VUELTAS int not null,
    CLIMA nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'parada_box')
CREATE TABLE GD_GESTION_DE_VAGOS.parada_box(
    ID int IDENTITY PRIMARY KEY,
    ID_AUTO decimal(18,0) REFERENCES GD_GESTION_DE_VAGOS.auto  not null,
    ID_CARRERA int REFERENCES GD_GESTION_DE_VAGOS.carrera  not null,
    TIEMPO_PARADA decimal(18,2) not null,
    NRO_VUELTA decimal(18,0) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'cambio_neumatico')
CREATE TABLE GD_GESTION_DE_VAGOS.cambio_neumatico(
ID int IDENTITY PRIMARY KEY,
ID_PARADA_BOX int REFERENCES GD_GESTION_DE_VAGOS.parada_box  not null,
ID_NEUMATICO_VIEJO int REFERENCES GD_GESTION_DE_VAGOS.neumatico  not null,
ID_NEUMATICO_NUEVO int REFERENCES GD_GESTION_DE_VAGOS.neumatico  not null,
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'bandera')
CREATE TABLE GD_GESTION_DE_VAGOS.bandera(
ID int IDENTITY PRIMARY KEY,
COLOR nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'incidente')
CREATE TABLE GD_GESTION_DE_VAGOS.incidente(
ID int IDENTITY PRIMARY KEY,
BANDERA int REFERENCES GD_GESTION_DE_VAGOS.bandera not null,
TIEMPO decimal(18,2) not null
);


IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'tipo_incidente')
CREATE TABLE GD_GESTION_DE_VAGOS.tipo_incidente(
ID int IDENTITY PRIMARY KEY,
NOMBRE nvarchar(255) not null
);


IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'auto_incidente')
CREATE TABLE GD_GESTION_DE_VAGOS.auto_incidente(
ID int IDENTITY PRIMARY KEY,
ID_AUTO decimal(18,0) REFERENCES GD_GESTION_DE_VAGOS.auto  not null,
ID_TIPO_INCIDENTE int REFERENCES GD_GESTION_DE_VAGOS.tipo_incidente not null,
ID_INCIDENTE int REFERENCES GD_GESTION_DE_VAGOS.incidente not null,
NRO_VUELTA decimal(18,0) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'tipo_sector')
CREATE TABLE GD_GESTION_DE_VAGOS.tipo_sector(
    ID int IDENTITY PRIMARY KEY,
	NOMBRE nvarchar(255) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'sector')
CREATE TABLE GD_GESTION_DE_VAGOS.sector(
    ID int IDENTITY PRIMARY KEY,
    ID_CIRCUITO int REFERENCES GD_GESTION_DE_VAGOS.circuito  not null,
	ID_TIPO_SECTOR int REFERENCES GD_GESTION_DE_VAGOS.tipo_sector not null,
	DISTANCIA decimal(18,2) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'medicion')
CREATE TABLE GD_GESTION_DE_VAGOS.medicion(
ID int IDENTITY PRIMARY KEY,
ID_AUTO decimal(18,0) REFERENCES GD_GESTION_DE_VAGOS.auto  not null,
ID_CARRERA int REFERENCES GD_GESTION_DE_VAGOS.carrera  not null,
ID_SECTOR int REFERENCES GD_GESTION_DE_VAGOS.sector  not null,
ID_TELE_MOTOR int REFERENCES GD_GESTION_DE_VAGOS.telemetria_motor  not null,
ID_TELE_CAJA int REFERENCES GD_GESTION_DE_VAGOS.telemetria_caja_de_cambios  not null,
DIST_VUELTA decimal(18,2) not null,
TIEMPO_VUELTA decimal(18,2) not null,
POSICION nvarchar(255) not null,
VELOCIDAD decimal(18,2) not null,
COMBUSTIBLE decimal(18,2) not null,
NRO_VUELTA int not null,
DIST_CARRERA decimal(18,2) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'telemetria_freno')
CREATE TABLE GD_GESTION_DE_VAGOS.telemetria_freno(
ID int IDENTITY PRIMARY KEY,
ID_MEDICION int REFERENCES GD_GESTION_DE_VAGOS.medicion  not null,
GROSOR_PASTILLA decimal(18,2) not null,
TEMPERATURA decimal(18,2) not null
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'telemetria_neumatico')
CREATE TABLE GD_GESTION_DE_VAGOS.telemetria_neumatico(
ID int IDENTITY PRIMARY KEY,
ID_NEUMATICO  int REFERENCES GD_GESTION_DE_VAGOS.neumatico  not null,
ID_MEDICION int REFERENCES GD_GESTION_DE_VAGOS.medicion  not null,
PROFUNDIDAD decimal(18,6) not null,
POSICION nvarchar(255) not null,
PRESION decimal(18,6) not null,
TEMPERATURA decimal(18,6) not null
);


-- Creamos las stored procedures

-- FALTA MODELO
-- ASUMO QUE EL ID ES EL NÚMERO DE SERIE (CHEQUEAR)
CREATE PROCEDURE migracion_telemetria_motor
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.telemetria_motor (ID, TEMP_ACEITE, TEMP_AGUA, RPM, POTENCIA)
	SELECT DISTINCT TELE_MOTOR_NRO_SERIE, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_RPM, TELE_MOTOR_TEMP_POTENCIA
	FROM gd_esquema.Maestra
	WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL
  END
GO

-- FALTA MODELO
-- ASUMO QUE EL ID ES EL NUMERO DE SERIE (CHEQUEAR)
CREATE PROCEDURE migracion_telemetria_caja_de_cambios
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.telemetria_caja_de_cambios (ID, TEMP_ACEITE, RPM, POTENCIA)
	SELECT DISTINCT TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE
	FROM gd_esquema.Maestra
	WHERE TELE_CAJA_NRO_SERIE IS NOT NULL
  END
GO

-- ACÁ ENTIENDO QUE NO TENDRÍAMOS QUE PONER (EN EL SELECT DISTINCT) ID, ID CARRERA, ID SECTOR, ID MOTOR, ID CAJA PORQUE NO ESTÁN
-- EN LA TABLA DE ELLOS PERO LOS DEJO POR LAS DUDAS. 
-- YO SUPONGO QUE HAY QUE SACARLOS PORQUE ESTO ES SOLO PARA MIGRAR LOS DATOS, LOS CAMPOS YA ESTÁN CREADOS ARRIBA EN LOS "CREATE TABLE"
-- ESTÁ DOS VECES TELE_AUTO_CODIGO PORQUE NO SÉ QUÉ PONER EN "ID" (POR ESO ESTIMO QUE NO VA NI ESE NI EL RESTO)
CREATE PROCEDURE migracion_medicion
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.medicion (ID, ID_AUTO, ID_CARRERA, ID_SECTOR, ID_TELE_MOTOR, ID_TELE_CAJA, DIST_VUELTA, TIEMPO_VUELTA, POSICION, VELOCIDAD, COMBUSTIBLE, NRO_VUELTA, DIST_CARRERA)
	SELECT DISTINCT TELE_AUTO_CODIGO, TELE_AUTO_CODIGO, TELE_ID_CARRERA, TELE_ID_SECTOR, TELE_ID_MOTOR, TELE_ID_CAJA, TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_TIEMPO_VUELTA, TELE_AUTO_POSICION, TELE_AUTO_VELOCIDAD, TELE_AUTO_COMBUSTIBLE, TELE_AUTO_NUMERO_VUELTA, TELE_AUTO_DISTANCIA_CARRERA
	FROM gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
  END
GO

-- HAY QUE VER CÓMO HACER CON LOS FRENOS Y NEUMÁTICOS PORQUE EN EL MODELO DE ELLOS HAY 4 DE CADA UNO Y NOSOTROS
-- TENEMOS UNA TABLA PARA NEUMATICO Y UNA PARA FRENO

-- CARRERA_CIRCUITO NO EXISTE EN LA TABLA DE ELLOS (LO PUSE SOLO PARA PONER ALGO)
-- ENTIENDO QUE DEBERÍAMOS SACARLO DEL 'SELECT DISTINCT'. 
-- ELLOS TIENEN UN CAMPO 'CARRERA_TOTAL_CARRERA' QUE NO SÉ QUÉ FUNCIÓN CUMPLE
CREATE PROCEDURE migracion_carrera
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.carrera (ID, ID_CIRCUITO, FECHA, MAX_VUELTAS, CLIMA)
	SELECT DISTINCT CODIGO_CARRERA, CARRERA_CIRCUITO, CARRERA_FECHA, CARRERA_CANT_VUELTAS, CARRERA_CLIMA
	FROM gd_esquema.Maestra
	WHERE CODIGO_CARRERA IS NOT NULL
  END
GO

-- EN SU MODELO CIRCUITO_PAIS ES UN NVARCHAR Y NOSOTROS TENEMOS EL ID COMO INT (IGUAL LO PONGO Y DESPUÉS VEMOS QUÉ HACEMOS)
CREATE PROCEDURE migracion_circuito
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.circuito (ID, ID_PAIS, NOMBRE)
	SELECT DISTINCT CIRCUITO_CODIGO, CIRCUITO_PAIS, CIRCUITO_NOMBRE
	FROM gd_esquema.Maestra
	WHERE CIRCUITO_CODIGO IS NOT NULL
  END
GO

CREATE PROCEDURE migracion_circuito
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.sector (ID, NOMBRE)
	SELECT DISTINCT CODIGO_SECTOR -- ELLOS TIENEN SECTOR_DISTANCIA Y SECTOR_TIPO, NO SÉ DE DÓNDE SACAR EL NOMBRE
	FROM gd_esquema.Maestra
	WHERE CODIGO_SECTOR IS NOT NULL
  END
GO

-- ELLOS NO TIENEN ID DE INCIDENTE, TIENEN BANDERA, NUMERO DE VUELTA, TIEMPO Y TIPO
CREATE PROCEDURE migracion_incidente
 AS
  BEGIN
    INSERT INTO GD_GESTION_DE_VAGOS.incidente (ID, BANDERA, TIEMPO)
	SELECT DISTINCT ????, INCIDENTE_BANDERA, INCIDENTE_TIEMPO -- ELLOS TIENEN SECTOR_DISTANCIA Y SECTOR_TIPO, NO SÉ DE DÓNDE SACAR EL NOMBRE (Y NOSOTROS NO TENEMOS EL TIPO AHÍ)
	FROM gd_esquema.Maestra
	WHERE ????? IS NOT NULL
  END
GO

